
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/fundoo?useSSL=false
    username: root
    password: Admin@123
  mail:
    username: ${mail}
    password: ${password}
aws:
  s3:
    bucket: ${bucketname}
    access: ${accesskey}
    secret: ${secretkey}
    region: ${region}
server:
  port: 8080
  
---
spring:
  profiles: staging
  datasource:
    url: jdbc:mysql://${dbhost}:3306/${database}?useSSL=false
    username: ${dbuser}
    password: ${dbpassword}
aws:
  s3:
    bucket: ${bucketname}
    access: ${accesskey}
    secret: ${secretkey}
    region: ${region}
server:
  port: 8080
---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://${dbhost}:3306/${database}?useSSL=false
    username: ${dbuser}
    password: ${dbpassword}
aws:
  s3:
    bucket: ${bucketname}
    access: ${accesskey}
    secret: ${secretkey}
    region: ${region}
server:
  port: 8080
  
